libraries: they are collection of modules and functions to perform specific tasks.

Pandas: data manipulation
Numpy(Numerical Python): multidimensional arrays and mathematical operations

matplotlib,seaborn,plotly: data visualization

statistics:

sklearn (scikit learn): machine learning
keras: deep learning

tensorflow: google

pytorch: facebook

Pandas are used for data manipulation, and we can create series data and dataframes data uning pandas

series: contains 1D data

Dataframe: contains 2D data

In [1]:
import pandas as pd

In [2]:
pd.Series([1,2,3,4,5])

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [3]:
dict1 = {'id':[1,2,3],
         'name':['Anik','Raj','Sankhanil'],
         'email':['a@gmail.com','b@gmail.com','c@gmail.com'],
         'salary':[100,200,300]
}
dict1

{'id': [1, 2, 3],
 'name': ['Anik', 'Raj', 'Sankhanil'],
 'email': ['a@gmail.com', 'b@gmail.com', 'c@gmail.com'],
 'salary': [100, 200, 300]}

In [4]:
df = pd.DataFrame(dict1)
df

   id       name        email  salary
0   1       Anik  a@gmail.com     100
1   2        Raj  b@gmail.com     200
2   3  Sankhanil  c@gmail.com     300

In [5]:
df_emp_data = pd.read_excel('data/emp_data.xlsx')
df_emp_data

   eid ename   sal  dept
0    1    aa  1234    10
1    2    bb  2345    20
2    3    cc  3214    30
3    4    dd  5332    40

In [6]:
df_mtcars = pd.read_csv('data/mtcars.csv')
df_mtcars

,manufacturer,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

In [7]:
df_studata = pd.read_csv('data/studata.txt')
df_studata

   sid    sname            emialid address  phoneno
0    1    priya    priya@gmail.com     dvg     9876
1    2  karthik  karthik@gmail.com     blr    12345
2    3    karan                NaN     msr    34567

In [8]:
df_chipotle = pd.read_csv('data/chipotle.tsv', sep='\t')
df_chipotle

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

## reading top 10 data

In [9]:
df_chipotle.head(10)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
6,3,1,Side of Chips,NaN,$1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25

In [10]:
# reading bottom 10
df_chipotle.tail(10)

,order_id,quantity,item_name,choice_description,item_price
4612,1831,1,Carnitas Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$9.25
4613,1831,1,Chips,NaN,$2.15
4614,1831,1,Bottled Water,NaN,$1.50
4615,1832,1,Chicken Soft Tacos,"[Fresh Tomato Salsa, [Rice, Cheese, Sour Cream]]",$8.75
4616,1832,1,Chips and Guacamole,NaN,$4.45
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [11]:
temp = df_chipotle.sample(10)
temp

,order_id,quantity,item_name,choice_description,item_price
1660,671,1,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$8.49
4145,1658,1,Chips and Guacamole,NaN,$4.45
3978,1594,1,Chips and Fresh Tomato Salsa,NaN,$2.95
2782,1104,1,Chips,NaN,$2.15
3234,1294,1,Veggie Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$8.75
2815,1117,1,Bottled Water,NaN,$1.09
3782,1514,1,Chips and Guacamole,NaN,$4.45
4137,1655,3,Bottled Water,NaN,$4.50
2339,932,2,Chicken Bowl,"[[Fresh Tomato Salsa (Mild), Roasted Chili Cor...",$16.98
3476,1396,1,Canned Soda,[Coca Cola],$1.09

In [12]:
# size chipotle data
df_chipotle.shape

(4622, 5)

In [13]:
# checking only rows
df_chipotle.shape[0]

4622

In [14]:
# check columns
df_chipotle.columns

Index(['order_id', 'quantity', 'item_name', 'choice_description',
       'item_price'],
      dtype='str')

In [15]:
# checking datatypes
df_chipotle.dtypes

order_id              int64
quantity              int64
item_name               str
choice_description      str
item_price              str
dtype: object

In [16]:
# check null values of each column
df_chipotle.isna().sum()

order_id                 0
quantity                 0
item_name                0
choice_description    1246
item_price               0
dtype: int64

In [17]:
# same with emp_data

In [18]:
# top 10
df_emp_data.head(10)

   eid ename   sal  dept
0    1    aa  1234    10
1    2    bb  2345    20
2    3    cc  3214    30
3    4    dd  5332    40

In [19]:
# bottom 10
df_emp_data.tail(10)

   eid ename   sal  dept
0    1    aa  1234    10
1    2    bb  2345    20
2    3    cc  3214    30
3    4    dd  5332    40

In [20]:
# shape
df_emp_data.shape

(4, 4)

In [21]:
# datatypes
df_emp_data.dtypes

eid      int64
ename      str
sal      int64
dept     int64
dtype: object

In [22]:
# check null values of each column
df_emp_data.isna().sum()

eid      0
ename    0
sal      0
dept     0
dtype: int64

In [23]:
df_chipotle.duplicated().sum()

np.int64(59)

In [24]:
df_mtcars.duplicated().sum()

np.int64(0)

In [25]:
# check datatypes
# check duplicates
# check null values

In [26]:
# How to extract individual column
df_mtcars.manufacturer

0               Mazda RX4
1           Mazda RX4 Wag
2              Datsun 710
3          Hornet 4 Drive
4       Hornet Sportabout
5                 Valiant
6              Duster 360
7               Merc 240D
8                Merc 230
9                Merc 280
10              Merc 280C
11             Merc 450SE
12             Merc 450SL
13            Merc 450SLC
14     Cadillac Fleetwood
15    Lincoln Continental
16      Chrysler Imperial
17               Fiat 128
18            Honda Civic
19         Toyota Corolla
20          Toyota Corona
21       Dodge Challenger
22            AMC Javelin
23             Camaro Z28
24       Pontiac Firebird
25              Fiat X1-9
26          Porsche 914-2
27           Lotus Europa
28         Ford Pantera L
29           Ferrari Dino
30          Maserati Bora
31             Volvo 142E
Name: manufacturer, dtype: str

In [27]:
df_mtcars['manufacturer']

0               Mazda RX4
1           Mazda RX4 Wag
2              Datsun 710
3          Hornet 4 Drive
4       Hornet Sportabout
5                 Valiant
6              Duster 360
7               Merc 240D
8                Merc 230
9                Merc 280
10              Merc 280C
11             Merc 450SE
12             Merc 450SL
13            Merc 450SLC
14     Cadillac Fleetwood
15    Lincoln Continental
16      Chrysler Imperial
17               Fiat 128
18            Honda Civic
19         Toyota Corolla
20          Toyota Corona
21       Dodge Challenger
22            AMC Javelin
23             Camaro Z28
24       Pontiac Firebird
25              Fiat X1-9
26          Porsche 914-2
27           Lotus Europa
28         Ford Pantera L
29           Ferrari Dino
30          Maserati Bora
31             Volvo 142E
Name: manufacturer, dtype: str

In [28]:
# in dataframe format
df_mtcars[['manufacturer']]

           manufacturer
0             Mazda RX4
1         Mazda RX4 Wag
2            Datsun 710
3        Hornet 4 Drive
4     Hornet Sportabout
5               Valiant
6            Duster 360
7             Merc 240D
8              Merc 230
9              Merc 280
10            Merc 280C
11           Merc 450SE
12           Merc 450SL
13          Merc 450SLC
14   Cadillac Fleetwood
15  Lincoln Continental
16    Chrysler Imperial
17             Fiat 128
18          Honda Civic
19       Toyota Corolla
20        Toyota Corona
21     Dodge Challenger
22          AMC Javelin
23           Camaro Z28
24     Pontiac Firebird
25            Fiat X1-9
26        Porsche 914-2
27         Lotus Europa
28       Ford Pantera L
29         Ferrari Dino
30        Maserati Bora
31           Volvo 142E

In [29]:
# mpg wt vs am
df_mtcars[['mpg','wt','vs','am']]

# storing in variable
temp_mtcars = df_mtcars[['mpg','wt','vs','am']]
temp_mtcars

     mpg     wt  vs  am
0   21.0  2.620   0   1
1   21.0  2.875   0   1
2   22.8  2.320   1   1
3   21.4  3.215   1   0
4   18.7  3.440   0   0
5   18.1  3.460   1   0
6   14.3  3.570   0   0
7   24.4  3.190   1   0
8   22.8  3.150   1   0
9   19.2  3.440   1   0
10  17.8  3.440   1   0
11  16.4  4.070   0   0
12  17.3  3.730   0   0
13  15.2  3.780   0   0
14  10.4  5.250   0   0
15  10.4  5.424   0   0
16  14.7  5.345   0   0
17  32.4  2.200   1   1
18  30.4  1.615   1   1
19  33.9  1.835   1   1
20  21.5  2.465   1   0
21  15.5  3.520   0   0
22  15.2  3.435   0   0
23  13.3  3.840   0   0
24  19.2  3.845   0   0
25  27.3  1.935   1   1
26  26.0  2.140   0   1
27  30.4  1.513   1   1
28  15.8  3.170   0   1
29  19.7  2.770   0   1
30  15.0  3.570   0   1
31  21.4  2.780   1   1

In [30]:
# rename column wt by weight and manufacturer as manu
df_mtcars.rename(columns={'manufacturer':'manu','wt':'weight'}, inplace=True)
df_mtcars.head()

,manu,mpg,cyl,disp,hp,drat,weight,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [31]:
# count how many unique vakyes are there in cyl column
df_mtcars['cyl'].nunique()

3

In [32]:
# print unique elements
df_mtcars['cyl'].unique()

array([6, 4, 8])

In [33]:
# each column , number of unique
df_mtcars.nunique()

manu      32
mpg       25
cyl        3
disp      27
hp        22
drat      22
weight    29
qsec      30
vs         2
am         2
gear       3
carb       6
dtype: int64

In [34]:
# non-quantitative means where no mathmatical operation is performed

In [35]:
# create a column called half_qsec

df_mtcars['half_qsec'] = round(df_mtcars['qsec']/2,2)

In [36]:
df_mtcars

,manu,mpg,cyl,disp,hp,drat,weight,qsec,vs,am,gear,carb,half_qsec
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4,8.23
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4,8.51
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1,9.30
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1,9.72
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2,8.51
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1,10.11
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4,7.92
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2,10.00
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2,11.45
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4,9.15
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4,9.45
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3,8.70
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3,8.80
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3,9.00
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4,8.99
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4,8.91
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4,8.71
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1,9.74
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2,9.26
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1,9.95
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1,10.01
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2,8.44
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2,8.65
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4,7.70
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2,8.52
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1,9.45
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2,8.35
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2,8.45
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4,7.25
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6,7.75
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8,7.30
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2,9.30

In [37]:
# create a column car_type
df_mtcars['car_type'] = df_mtcars['am'].map({1:'Automatic',0:'Manual'})

In [38]:
df_mtcars

,manu,mpg,cyl,disp,hp,drat,weight,qsec,vs,am,gear,carb,half_qsec,car_type
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4,8.23,Automatic
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4,8.51,Automatic
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1,9.30,Automatic
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1,9.72,Manual
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2,8.51,Manual
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1,10.11,Manual
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4,7.92,Manual
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2,10.00,Manual
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2,11.45,Manual
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4,9.15,Manual
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4,9.45,Manual
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3,8.70,Manual
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3,8.80,Manual
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3,9.00,Manual
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4,8.99,Manual
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4,8.91,Manual
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4,8.71,Manual
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1,9.74,Automatic
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2,9.26,Automatic
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1,9.95,Automatic
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1,10.01,Manual
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2,8.44,Manual
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2,8.65,Manual
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4,7.70,Manual
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2,8.52,Manual
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1,9.45,Automatic
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2,8.35,Automatic
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2,8.45,Automatic
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4,7.25,Automatic
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6,7.75,Automatic
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8,7.30,Automatic
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2,9.30,Automatic

In [39]:
df_mtcars["car_type1"] = ["Manual" if x == 0 else "Automatic" for x in df_mtcars["am"]]

In [40]:
df_mtcars

,manu,mpg,cyl,disp,hp,drat,weight,qsec,vs,am,gear,carb,half_qsec,car_type,car_type1
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4,8.23,Automatic,Automatic
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4,8.51,Automatic,Automatic
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1,9.30,Automatic,Automatic
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1,9.72,Manual,Manual
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2,8.51,Manual,Manual
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1,10.11,Manual,Manual
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4,7.92,Manual,Manual
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2,10.00,Manual,Manual
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2,11.45,Manual,Manual
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4,9.15,Manual,Manual
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4,9.45,Manual,Manual
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3,8.70,Manual,Manual
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3,8.80,Manual,Manual
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3,9.00,Manual,Manual
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4,8.99,Manual,Manual
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4,8.91,Manual,Manual
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4,8.71,Manual,Manual
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1,9.74,Automatic,Automatic
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2,9.26,Automatic,Automatic
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1,9.95,Automatic,Automatic
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1,10.01,Manual,Manual
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2,8.44,Manual,Manual
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2,8.65,Manual,Manual
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4,7.70,Manual,Manual
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2,8.52,Manual,Manual
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1,9.45,Automatic,Automatic
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2,8.35,Automatic,Automatic
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2,8.45,Automatic,Automatic
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4,7.25,Automatic,Automatic
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6,7.75,Automatic,Automatic
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8,7.30,Automatic,Automatic
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2,9.30,Automatic,Automatic

In [41]:
df_mtcars['car_type1'] = df_mtcars['am'].apply(lambda x: "Manual" if x == 0 else "Automatic")
df_mtcars.head()

,manu,mpg,cyl,disp,hp,drat,weight,qsec,vs,am,gear,carb,half_qsec,car_type,car_type1
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4,8.23,Automatic,Automatic
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4,8.51,Automatic,Automatic
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1,9.30,Automatic,Automatic
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1,9.72,Manual,Manual
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2,8.51,Manual,Manual

In [42]:
# changing present columns
df_mtcars['disp'] -= 10
df_mtcars.head()

,manu,mpg,cyl,disp,hp,drat,weight,qsec,vs,am,gear,carb,half_qsec,car_type,car_type1
0,Mazda RX4,21.0,6,150.0,110,3.90,2.620,16.46,0,1,4,4,8.23,Automatic,Automatic
1,Mazda RX4 Wag,21.0,6,150.0,110,3.90,2.875,17.02,0,1,4,4,8.51,Automatic,Automatic
2,Datsun 710,22.8,4,98.0,93,3.85,2.320,18.61,1,1,4,1,9.30,Automatic,Automatic
3,Hornet 4 Drive,21.4,6,248.0,110,3.08,3.215,19.44,1,0,3,1,9.72,Manual,Manual
4,Hornet Sportabout,18.7,8,350.0,175,3.15,3.440,17.02,0,0,3,2,8.51,Manual,Manual

In [43]:
# deleting columns
del df_mtcars['half_qsec']
df_mtcars.head()

,manu,mpg,cyl,disp,hp,drat,weight,qsec,vs,am,gear,carb,car_type,car_type1
0,Mazda RX4,21.0,6,150.0,110,3.90,2.620,16.46,0,1,4,4,Automatic,Automatic
1,Mazda RX4 Wag,21.0,6,150.0,110,3.90,2.875,17.02,0,1,4,4,Automatic,Automatic
2,Datsun 710,22.8,4,98.0,93,3.85,2.320,18.61,1,1,4,1,Automatic,Automatic
3,Hornet 4 Drive,21.4,6,248.0,110,3.08,3.215,19.44,1,0,3,1,Manual,Manual
4,Hornet Sportabout,18.7,8,350.0,175,3.15,3.440,17.02,0,0,3,2,Manual,Manual

In [44]:
# deleting multiple columns
df_mtcars.drop(columns=['car_type','car_type1'], inplace=True)
df_mtcars

,manu,mpg,cyl,disp,hp,drat,weight,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,150.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,150.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,98.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,248.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,350.0,175,3.15,3.440,17.02,0,0,3,2
5,Valiant,18.1,6,215.0,105,2.76,3.460,20.22,1,0,3,1
6,Duster 360,14.3,8,350.0,245,3.21,3.570,15.84,0,0,3,4
7,Merc 240D,24.4,4,136.7,62,3.69,3.190,20.00,1,0,4,2
8,Merc 230,22.8,4,130.8,95,3.92,3.150,22.90,1,0,4,2
9,Merc 280,19.2,6,157.6,123,3.92,3.440,18.30,1,0,4,4
10,Merc 280C,17.8,6,157.6,123,3.92,3.440,18.90,1,0,4,4
11,Merc 450SE,16.4,8,265.8,180,3.07,4.070,17.40,0,0,3,3
12,Merc 450SL,17.3,8,265.8,180,3.07,3.730,17.60,0,0,3,3
13,Merc 450SLC,15.2,8,265.8,180,3.07,3.780,18.00,0,0,3,3
14,Cadillac Fleetwood,10.4,8,462.0,205,2.93,5.250,17.98,0,0,3,4
15,Lincoln Continental,10.4,8,450.0,215,3.00,5.424,17.82,0,0,3,4
16,Chrysler Imperial,14.7,8,430.0,230,3.23,5.345,17.42,0,0,3,4
17,Fiat 128,32.4,4,68.7,66,4.08,2.200,19.47,1,1,4,1
18,Honda Civic,30.4,4,65.7,52,4.93,1.615,18.52,1,1,4,2
19,Toyota Corolla,33.9,4,61.1,65,4.22,1.835,19.90,1,1,4,1
20,Toyota Corona,21.5,4,110.1,97,3.70,2.465,20.01,1,0,3,1
21,Dodge Challenger,15.5,8,308.0,150,2.76,3.520,16.87,0,0,3,2
22,AMC Javelin,15.2,8,294.0,150,3.15,3.435,17.30,0,0,3,2
23,Camaro Z28,13.3,8,340.0,245,3.73,3.840,15.41,0,0,3,4
24,Pontiac Firebird,19.2,8,390.0,175,3.08,3.845,17.05,0,0,3,2
25,Fiat X1-9,27.3,4,69.0,66,4.08,1.935,18.90,1,1,4,1
26,Porsche 914-2,26.0,4,110.3,91,4.43,2.140,16.70,0,1,5,2
27,Lotus Europa,30.4,4,85.1,113,3.77,1.513,16.90,1,1,5,2
28,Ford Pantera L,15.8,8,341.0,264,4.22,3.170,14.50,0,1,5,4
29,Ferrari Dino,19.7,6,135.0,175,3.62,2.770,15.50,0,1,5,6
30,Maserati Bora,15.0,8,291.0,335,3.54,3.570,14.60,0,1,5,8
31,Volvo 142E,21.4,4,111.0,109,4.11,2.780,18.60,1,1,4,2

In [45]:
# calculate mean, medain, total, max, min value of mpg column
df_mtcars['mpg'].mean()

np.float64(20.090625000000003)

In [46]:
df_mtcars['mpg'].median()

np.float64(19.2)

In [47]:
df_mtcars['mpg'].sum()

np.float64(642.9000000000001)

In [48]:
df_mtcars['mpg'].max()

np.float64(33.9)

In [49]:
df_mtcars['mpg'].min()

np.float64(10.4)

In [50]:
# describe
df_mtcars['mpg'].describe()

count    32.000000
mean     20.090625
std       6.026948
min      10.400000
25%      15.425000
50%      19.200000
75%      22.800000
max      33.900000
Name: mpg, dtype: float64

In [51]:
# 1st five rows and 1st five columns
'''
DataFrame slicing:
1. iloc: using index values of ro and column
    var.iloc[rst:rsp:rss,cst:csp:css]
default start value: 0
    stop value:upto end
    step size: 1


'''
df_mtcars.iloc[:5,:5]

                manu   mpg  cyl   disp   hp
0          Mazda RX4  21.0    6  150.0  110
1      Mazda RX4 Wag  21.0    6  150.0  110
2         Datsun 710  22.8    4   98.0   93
3     Hornet 4 Drive  21.4    6  248.0  110
4  Hornet Sportabout  18.7    8  350.0  175

In [52]:
df_mtcars.head(5)[df_mtcars.columns[:5]]
df_mtcars[df_mtcars.columns[:5]].head(5)

                manu   mpg  cyl   disp   hp
0          Mazda RX4  21.0    6  150.0  110
1      Mazda RX4 Wag  21.0    6  150.0  110
2         Datsun 710  22.8    4   98.0   93
3     Hornet 4 Drive  21.4    6  248.0  110
4  Hornet Sportabout  18.7    8  350.0  175

In [53]:
df_mtcars.loc[df_mtcars.index[:5],df_mtcars.columns[:5]]

                manu   mpg  cyl   disp   hp
0          Mazda RX4  21.0    6  150.0  110
1      Mazda RX4 Wag  21.0    6  150.0  110
2         Datsun 710  22.8    4   98.0   93
3     Hornet 4 Drive  21.4    6  248.0  110
4  Hornet Sportabout  18.7    8  350.0  175

In [54]:
# Extract all the rows with last 5 columns
df_mtcars.iloc[:,-5:]

     qsec  vs  am  gear  carb
0   16.46   0   1     4     4
1   17.02   0   1     4     4
2   18.61   1   1     4     1
3   19.44   1   0     3     1
4   17.02   0   0     3     2
5   20.22   1   0     3     1
6   15.84   0   0     3     4
7   20.00   1   0     4     2
8   22.90   1   0     4     2
9   18.30   1   0     4     4
10  18.90   1   0     4     4
11  17.40   0   0     3     3
12  17.60   0   0     3     3
13  18.00   0   0     3     3
14  17.98   0   0     3     4
15  17.82   0   0     3     4
16  17.42   0   0     3     4
17  19.47   1   1     4     1
18  18.52   1   1     4     2
19  19.90   1   1     4     1
20  20.01   1   0     3     1
21  16.87   0   0     3     2
22  17.30   0   0     3     2
23  15.41   0   0     3     4
24  17.05   0   0     3     2
25  18.90   1   1     4     1
26  16.70   0   1     5     2
27  16.90   1   1     5     2
28  14.50   0   1     5     4
29  15.50   0   1     5     6
30  14.60   0   1     5     8
31  18.60   1   1     4     2

In [55]:
# print table in reverse
df_mtcars.iloc[::-1,::-1]

,carb,gear,am,vs,qsec,weight,drat,hp,disp,cyl,mpg,manu
31,2,4,1,1,18.60,2.780,4.11,109,111.0,4,21.4,Volvo 142E
30,8,5,1,0,14.60,3.570,3.54,335,291.0,8,15.0,Maserati Bora
29,6,5,1,0,15.50,2.770,3.62,175,135.0,6,19.7,Ferrari Dino
28,4,5,1,0,14.50,3.170,4.22,264,341.0,8,15.8,Ford Pantera L
27,2,5,1,1,16.90,1.513,3.77,113,85.1,4,30.4,Lotus Europa
26,2,5,1,0,16.70,2.140,4.43,91,110.3,4,26.0,Porsche 914-2
25,1,4,1,1,18.90,1.935,4.08,66,69.0,4,27.3,Fiat X1-9
24,2,3,0,0,17.05,3.845,3.08,175,390.0,8,19.2,Pontiac Firebird
23,4,3,0,0,15.41,3.840,3.73,245,340.0,8,13.3,Camaro Z28
22,2,3,0,0,17.30,3.435,3.15,150,294.0,8,15.2,AMC Javelin
21,2,3,0,0,16.87,3.520,2.76,150,308.0,8,15.5,Dodge Challenger
20,1,3,0,1,20.01,2.465,3.70,97,110.1,4,21.5,Toyota Corona
19,1,4,1,1,19.90,1.835,4.22,65,61.1,4,33.9,Toyota Corolla
18,2,4,1,1,18.52,1.615,4.93,52,65.7,4,30.4,Honda Civic
17,1,4,1,1,19.47,2.200,4.08,66,68.7,4,32.4,Fiat 128
16,4,3,0,0,17.42,5.345,3.23,230,430.0,8,14.7,Chrysler Imperial
15,4,3,0,0,17.82,5.424,3.00,215,450.0,8,10.4,Lincoln Continental
14,4,3,0,0,17.98,5.250,2.93,205,462.0,8,10.4,Cadillac Fleetwood
13,3,3,0,0,18.00,3.780,3.07,180,265.8,8,15.2,Merc 450SLC
12,3,3,0,0,17.60,3.730,3.07,180,265.8,8,17.3,Merc 450SL
11,3,3,0,0,17.40,4.070,3.07,180,265.8,8,16.4,Merc 450SE
10,4,4,0,1,18.90,3.440,3.92,123,157.6,6,17.8,Merc 280C
9,4,4,0,1,18.30,3.440,3.92,123,157.6,6,19.2,Merc 280
8,2,4,0,1,22.90,3.150,3.92,95,130.8,4,22.8,Merc 230
7,2,4,0,1,20.00,3.190,3.69,62,136.7,4,24.4,Merc 240D
6,4,3,0,0,15.84,3.570,3.21,245,350.0,8,14.3,Duster 360
5,1,3,0,1,20.22,3.460,2.76,105,215.0,6,18.1,Valiant
4,2,3,0,0,17.02,3.440,3.15,175,350.0,8,18.7,Hornet Sportabout
3,1,3,0,1,19.44,3.215,3.08,110,248.0,6,21.4,Hornet 4 Drive
2,1,4,1,1,18.61,2.320,3.85,93,98.0,4,22.8,Datsun 710
1,4,4,1,0,17.02,2.875,3.90,110,150.0,6,21.0,Mazda RX4 Wag
0,4,4,1,0,16.46,2.620,3.90,110,150.0,6,21.0,Mazda RX4

In [56]:
# print even index rows and odd indexed columns
df_mtcars.iloc[::2,1::2]

     mpg   disp  drat   qsec  am  carb
0   21.0  150.0  3.90  16.46   1     4
2   22.8   98.0  3.85  18.61   1     1
4   18.7  350.0  3.15  17.02   0     2
6   14.3  350.0  3.21  15.84   0     4
8   22.8  130.8  3.92  22.90   0     2
10  17.8  157.6  3.92  18.90   0     4
12  17.3  265.8  3.07  17.60   0     3
14  10.4  462.0  2.93  17.98   0     4
16  14.7  430.0  3.23  17.42   0     4
18  30.4   65.7  4.93  18.52   1     2
20  21.5  110.1  3.70  20.01   0     1
22  15.2  294.0  3.15  17.30   0     2
24  19.2  390.0  3.08  17.05   0     2
26  26.0  110.3  4.43  16.70   1     2
28  15.8  341.0  4.22  14.50   1     4
30  15.0  291.0  3.54  14.60   1     8

In [57]:
#
rows1 = [2,7,11,15,20,23,28]
col = [2,6,9,11]
df_mtcars.iloc[rows1,col]

    cyl  weight  am  carb
2     4   2.320   1     1
7     4   3.190   0     2
11    8   4.070   0     3
15    8   5.424   0     4
20    4   2.465   0     1
23    8   3.840   0     4
28    8   3.170   1     4

In [58]:
# loc: extracting data by location name
'''
var.loc[starting name:ending name]
'''

'\nvar.loc[starting name:ending name]\n'

In [59]:
# extract 1st 10 rows with 1st 4 columns
df_mtcars.loc[df_mtcars.index[:10],df_mtcars.columns[:4]]

                manu   mpg  cyl   disp
0          Mazda RX4  21.0    6  150.0
1      Mazda RX4 Wag  21.0    6  150.0
2         Datsun 710  22.8    4   98.0
3     Hornet 4 Drive  21.4    6  248.0
4  Hornet Sportabout  18.7    8  350.0
5            Valiant  18.1    6  215.0
6         Duster 360  14.3    8  350.0
7          Merc 240D  24.4    4  136.7
8           Merc 230  22.8    4  130.8
9           Merc 280  19.2    6  157.6

In [60]:
df_mtcars.loc[0:9,'manu':'disp']

                manu   mpg  cyl   disp
0          Mazda RX4  21.0    6  150.0
1      Mazda RX4 Wag  21.0    6  150.0
2         Datsun 710  22.8    4   98.0
3     Hornet 4 Drive  21.4    6  248.0
4  Hornet Sportabout  18.7    8  350.0
5            Valiant  18.1    6  215.0
6         Duster 360  14.3    8  350.0
7          Merc 240D  24.4    4  136.7
8           Merc 230  22.8    4  130.8
9           Merc 280  19.2    6  157.6

In [61]:
# reverse
df_mtcars.loc[df_mtcars.index[::-1],df_mtcars.columns[::-1]]

,carb,gear,am,vs,qsec,weight,drat,hp,disp,cyl,mpg,manu
31,2,4,1,1,18.60,2.780,4.11,109,111.0,4,21.4,Volvo 142E
30,8,5,1,0,14.60,3.570,3.54,335,291.0,8,15.0,Maserati Bora
29,6,5,1,0,15.50,2.770,3.62,175,135.0,6,19.7,Ferrari Dino
28,4,5,1,0,14.50,3.170,4.22,264,341.0,8,15.8,Ford Pantera L
27,2,5,1,1,16.90,1.513,3.77,113,85.1,4,30.4,Lotus Europa
26,2,5,1,0,16.70,2.140,4.43,91,110.3,4,26.0,Porsche 914-2
25,1,4,1,1,18.90,1.935,4.08,66,69.0,4,27.3,Fiat X1-9
24,2,3,0,0,17.05,3.845,3.08,175,390.0,8,19.2,Pontiac Firebird
23,4,3,0,0,15.41,3.840,3.73,245,340.0,8,13.3,Camaro Z28
22,2,3,0,0,17.30,3.435,3.15,150,294.0,8,15.2,AMC Javelin
21,2,3,0,0,16.87,3.520,2.76,150,308.0,8,15.5,Dodge Challenger
20,1,3,0,1,20.01,2.465,3.70,97,110.1,4,21.5,Toyota Corona
19,1,4,1,1,19.90,1.835,4.22,65,61.1,4,33.9,Toyota Corolla
18,2,4,1,1,18.52,1.615,4.93,52,65.7,4,30.4,Honda Civic
17,1,4,1,1,19.47,2.200,4.08,66,68.7,4,32.4,Fiat 128
16,4,3,0,0,17.42,5.345,3.23,230,430.0,8,14.7,Chrysler Imperial
15,4,3,0,0,17.82,5.424,3.00,215,450.0,8,10.4,Lincoln Continental
14,4,3,0,0,17.98,5.250,2.93,205,462.0,8,10.4,Cadillac Fleetwood
13,3,3,0,0,18.00,3.780,3.07,180,265.8,8,15.2,Merc 450SLC
12,3,3,0,0,17.60,3.730,3.07,180,265.8,8,17.3,Merc 450SL
11,3,3,0,0,17.40,4.070,3.07,180,265.8,8,16.4,Merc 450SE
10,4,4,0,1,18.90,3.440,3.92,123,157.6,6,17.8,Merc 280C
9,4,4,0,1,18.30,3.440,3.92,123,157.6,6,19.2,Merc 280
8,2,4,0,1,22.90,3.150,3.92,95,130.8,4,22.8,Merc 230
7,2,4,0,1,20.00,3.190,3.69,62,136.7,4,24.4,Merc 240D
6,4,3,0,0,15.84,3.570,3.21,245,350.0,8,14.3,Duster 360
5,1,3,0,1,20.22,3.460,2.76,105,215.0,6,18.1,Valiant
4,2,3,0,0,17.02,3.440,3.15,175,350.0,8,18.7,Hornet Sportabout
3,1,3,0,1,19.44,3.215,3.08,110,248.0,6,21.4,Hornet 4 Drive
2,1,4,1,1,18.61,2.320,3.85,93,98.0,4,22.8,Datsun 710
1,4,4,1,0,17.02,2.875,3.90,110,150.0,6,21.0,Mazda RX4 Wag
0,4,4,1,0,16.46,2.620,3.90,110,150.0,6,21.0,Mazda RX4

In [62]:
df_mtcars.loc[::-1,'carb':'manu':-1]
df_mtcars.loc[::-1,::-1]

,carb,gear,am,vs,qsec,weight,drat,hp,disp,cyl,mpg,manu
31,2,4,1,1,18.60,2.780,4.11,109,111.0,4,21.4,Volvo 142E
30,8,5,1,0,14.60,3.570,3.54,335,291.0,8,15.0,Maserati Bora
29,6,5,1,0,15.50,2.770,3.62,175,135.0,6,19.7,Ferrari Dino
28,4,5,1,0,14.50,3.170,4.22,264,341.0,8,15.8,Ford Pantera L
27,2,5,1,1,16.90,1.513,3.77,113,85.1,4,30.4,Lotus Europa
26,2,5,1,0,16.70,2.140,4.43,91,110.3,4,26.0,Porsche 914-2
25,1,4,1,1,18.90,1.935,4.08,66,69.0,4,27.3,Fiat X1-9
24,2,3,0,0,17.05,3.845,3.08,175,390.0,8,19.2,Pontiac Firebird
23,4,3,0,0,15.41,3.840,3.73,245,340.0,8,13.3,Camaro Z28
22,2,3,0,0,17.30,3.435,3.15,150,294.0,8,15.2,AMC Javelin
21,2,3,0,0,16.87,3.520,2.76,150,308.0,8,15.5,Dodge Challenger
20,1,3,0,1,20.01,2.465,3.70,97,110.1,4,21.5,Toyota Corona
19,1,4,1,1,19.90,1.835,4.22,65,61.1,4,33.9,Toyota Corolla
18,2,4,1,1,18.52,1.615,4.93,52,65.7,4,30.4,Honda Civic
17,1,4,1,1,19.47,2.200,4.08,66,68.7,4,32.4,Fiat 128
16,4,3,0,0,17.42,5.345,3.23,230,430.0,8,14.7,Chrysler Imperial
15,4,3,0,0,17.82,5.424,3.00,215,450.0,8,10.4,Lincoln Continental
14,4,3,0,0,17.98,5.250,2.93,205,462.0,8,10.4,Cadillac Fleetwood
13,3,3,0,0,18.00,3.780,3.07,180,265.8,8,15.2,Merc 450SLC
12,3,3,0,0,17.60,3.730,3.07,180,265.8,8,17.3,Merc 450SL
11,3,3,0,0,17.40,4.070,3.07,180,265.8,8,16.4,Merc 450SE
10,4,4,0,1,18.90,3.440,3.92,123,157.6,6,17.8,Merc 280C
9,4,4,0,1,18.30,3.440,3.92,123,157.6,6,19.2,Merc 280
8,2,4,0,1,22.90,3.150,3.92,95,130.8,4,22.8,Merc 230
7,2,4,0,1,20.00,3.190,3.69,62,136.7,4,24.4,Merc 240D
6,4,3,0,0,15.84,3.570,3.21,245,350.0,8,14.3,Duster 360
5,1,3,0,1,20.22,3.460,2.76,105,215.0,6,18.1,Valiant
4,2,3,0,0,17.02,3.440,3.15,175,350.0,8,18.7,Hornet Sportabout
3,1,3,0,1,19.44,3.215,3.08,110,248.0,6,21.4,Hornet 4 Drive
2,1,4,1,1,18.61,2.320,3.85,93,98.0,4,22.8,Datsun 710
1,4,4,1,0,17.02,2.875,3.90,110,150.0,6,21.0,Mazda RX4 Wag
0,4,4,1,0,16.46,2.620,3.90,110,150.0,6,21.0,Mazda RX4

In [63]:
# all records where gear = 4
df_mtcars[df_mtcars['gear'] == 4]

,manu,mpg,cyl,disp,hp,drat,weight,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,150.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,150.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,98.0,93,3.85,2.320,18.61,1,1,4,1
7,Merc 240D,24.4,4,136.7,62,3.69,3.190,20.00,1,0,4,2
8,Merc 230,22.8,4,130.8,95,3.92,3.150,22.90,1,0,4,2
9,Merc 280,19.2,6,157.6,123,3.92,3.440,18.30,1,0,4,4
10,Merc 280C,17.8,6,157.6,123,3.92,3.440,18.90,1,0,4,4
17,Fiat 128,32.4,4,68.7,66,4.08,2.200,19.47,1,1,4,1
18,Honda Civic,30.4,4,65.7,52,4.93,1.615,18.52,1,1,4,2
19,Toyota Corolla,33.9,4,61.1,65,4.22,1.835,19.90,1,1,4,1
25,Fiat X1-9,27.3,4,69.0,66,4.08,1.935,18.90,1,1,4,1
31,Volvo 142E,21.4,4,111.0,109,4.11,2.780,18.60,1,1,4,2

In [64]:
# try to extract 4 gear car with 6 cyl
df_mtcars[(df_mtcars['gear'] == 4) & (df_mtcars['cyl'] == 6)]

,manu,mpg,cyl,disp,hp,drat,weight,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,150.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,150.0,110,3.90,2.875,17.02,0,1,4,4
9,Merc 280,19.2,6,157.6,123,3.92,3.440,18.30,1,0,4,4
10,Merc 280C,17.8,6,157.6,123,3.92,3.440,18.90,1,0,4,4

In [65]:
# extract data either 2 carb or automatic cars details

df_mtcars[(df_mtcars['am'] == 1) | (df_mtcars['carb'] == 2)]

,manu,mpg,cyl,disp,hp,drat,weight,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,150.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,150.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,98.0,93,3.85,2.320,18.61,1,1,4,1
4,Hornet Sportabout,18.7,8,350.0,175,3.15,3.440,17.02,0,0,3,2
7,Merc 240D,24.4,4,136.7,62,3.69,3.190,20.00,1,0,4,2
8,Merc 230,22.8,4,130.8,95,3.92,3.150,22.90,1,0,4,2
17,Fiat 128,32.4,4,68.7,66,4.08,2.200,19.47,1,1,4,1
18,Honda Civic,30.4,4,65.7,52,4.93,1.615,18.52,1,1,4,2
19,Toyota Corolla,33.9,4,61.1,65,4.22,1.835,19.90,1,1,4,1
21,Dodge Challenger,15.5,8,308.0,150,2.76,3.520,16.87,0,0,3,2
22,AMC Javelin,15.2,8,294.0,150,3.15,3.435,17.30,0,0,3,2
24,Pontiac Firebird,19.2,8,390.0,175,3.08,3.845,17.05,0,0,3,2
25,Fiat X1-9,27.3,4,69.0,66,4.08,1.935,18.90,1,1,4,1
26,Porsche 914-2,26.0,4,110.3,91,4.43,2.140,16.70,0,1,5,2
27,Lotus Europa,30.4,4,85.1,113,3.77,1.513,16.90,1,1,5,2
28,Ford Pantera L,15.8,8,341.0,264,4.22,3.170,14.50,0,1,5,4
29,Ferrari Dino,19.7,6,135.0,175,3.62,2.770,15.50,0,1,5,6
30,Maserati Bora,15.0,8,291.0,335,3.54,3.570,14.60,0,1,5,8
31,Volvo 142E,21.4,4,111.0,109,4.11,2.780,18.60,1,1,4,2

In [66]:
# extract data who's hp between 110 and 120
df_mtcars[df_mtcars['hp'].between(110,120)]

,manu,mpg,cyl,disp,hp,drat,weight,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,150.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,150.0,110,3.90,2.875,17.02,0,1,4,4
3,Hornet 4 Drive,21.4,6,248.0,110,3.08,3.215,19.44,1,0,3,1
27,Lotus Europa,30.4,4,85.1,113,3.77,1.513,16.90,1,1,5,2

In [67]:
# extract data weight between 2 to 3 or cyl 6
df_mtcars[(df_mtcars['weight'].between(2,3)) | (df_mtcars['cyl'] == 6)]

,manu,mpg,cyl,disp,hp,drat,weight,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,150.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,150.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,98.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,248.0,110,3.08,3.215,19.44,1,0,3,1
5,Valiant,18.1,6,215.0,105,2.76,3.460,20.22,1,0,3,1
9,Merc 280,19.2,6,157.6,123,3.92,3.440,18.30,1,0,4,4
10,Merc 280C,17.8,6,157.6,123,3.92,3.440,18.90,1,0,4,4
17,Fiat 128,32.4,4,68.7,66,4.08,2.200,19.47,1,1,4,1
20,Toyota Corona,21.5,4,110.1,97,3.70,2.465,20.01,1,0,3,1
26,Porsche 914-2,26.0,4,110.3,91,4.43,2.140,16.70,0,1,5,2
29,Ferrari Dino,19.7,6,135.0,175,3.62,2.770,15.50,0,1,5,6
31,Volvo 142E,21.4,4,111.0,109,4.11,2.780,18.60,1,1,4,2