In [2]:
import pandas as pd
from numpy.ma.extras import unique, average

In [4]:
df = pd.read_csv('data/insurance.csv')
df

      age     sex   bmi  children smoker     region  expenses
0      19  female  27.9         0    yes  southwest  16884.92
1      18    male  33.8         1     no  southeast   1725.55
2      28    male  33.0         3     no  southeast   4449.46
3      33    male  22.7         0     no  northwest  21984.47
4      32    male  28.9         0     no  northwest   3866.86
...   ...     ...   ...       ...    ...        ...       ...
1333   50    male  31.0         3     no  northwest  10600.55
1334   18  female  31.9         0     no  northeast   2205.98
1335   18  female  36.9         0     no  southeast   1629.83
1336   21  female  25.8         0     no  southwest   2007.95
1337   61  female  29.1         0    yes  northwest  29141.36

[1338 rows x 7 columns]

In [6]:
# checking shape
df.shape

(1338, 7)

In [7]:
# checking datatypes
df.dtypes

age           int64
sex             str
bmi         float64
children      int64
smoker          str
region          str
expenses    float64
dtype: object

In [5]:
# check for null values of each column
df.isna().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
expenses    0
dtype: int64

In [8]:
# duplicates
df.duplicated().sum()

np.int64(1)

In [13]:
# each region wise total expenses
# gender wise avg bmi and expenses
# each region, each children and somker class wise total expenses
df.groupby('region')['expenses'].sum().sort_values(ascending=False)

region
southeast    5363689.80
northeast    4343668.64
northwest    4035711.93
southwest    4012754.82
Name: expenses, dtype: float64

In [12]:
# to get ans in dataframe
df.groupby("region", as_index=False)["expenses"].sum()

      region    expenses
0  northeast  4343668.64
1  northwest  4035711.93
2  southeast  5363689.80
3  southwest  4012754.82

In [22]:
# gender wise avg bmi and expenses
df.groupby('sex')[['bmi','expenses']].mean().round(2)

          bmi  expenses
sex
female  30.38  12569.58
male    30.95  13956.75

In [28]:
# each region, each children and somker class wise total expenses
df.groupby(['region','children','smoker'])[['expenses']].sum()

                             expenses
region    children smoker
northeast 0        no       976747.39
                   yes      732342.66
          1        no       544403.10
                   yes      711482.80
          2        no       490110.44
                   yes      204262.33
          3        no       221947.50
                   yes      340039.14
          4        no       101396.36
          5        no        20936.92
northwest 0        no       814816.76
                   yes      680000.21
          1        no       518805.68
                   yes      238233.23
          2        no       547296.76
                   yes      341347.99
          3        no       348081.14
                   yes      470082.25
          4        no        46609.63
                   yes       21472.48
          5        no         8965.80
southeast 0        no       826029.55
                   yes     1420619.78
          1        no       585202.76
                   yes      715066.23
          2        no       360936.28
                   yes      677142.84
          3        no       287678.69
                   yes      358065.90
          4        no        72255.12
          5        no        60692.65
southwest 0        no       876219.52
                   yes      771294.22
          1        no       535306.23
                   yes      276399.64
          2        no       357878.89
                   yes      638679.83
          3        no       276805.98
                   yes      108084.41
          4        no        46408.47
                   yes       58124.36
          5        no        48530.01
                   yes       19023.26

In [27]:
# each region, each children and somker class wise total expenses
pd.pivot_table(df,columns=['region','children','smoker'],values='expenses', aggfunc='sum')

region    northeast                                                       \
children          0                    1                    2
smoker           no        yes        no       yes         no        yes
expenses  976747.39  732342.66  544403.1  711482.8  490110.44  204262.33

region                                              ...  southwest             \
children         3                     4         5  ...          1
smoker          no        yes         no        no  ...         no        yes
expenses  221947.5  340039.14  101396.36  20936.92  ...  535306.23  276399.64

region                                                                    \
children          2                     3                    4
smoker           no        yes         no        yes        no       yes
expenses  357878.89  638679.83  276805.98  108084.41  46408.47  58124.36

region
children         5
smoker          no       yes
expenses  48530.01  19023.26

[1 rows x 43 columns]

In [29]:
pd.pivot_table(
    df,
    index=["region", "children"],
    columns="smoker",
    values="expenses",
    aggfunc="sum"
)

smoker                     no         yes
region    children
northeast 0         976747.39   732342.66
          1         544403.10   711482.80
          2         490110.44   204262.33
          3         221947.50   340039.14
          4         101396.36         NaN
          5          20936.92         NaN
northwest 0         814816.76   680000.21
          1         518805.68   238233.23
          2         547296.76   341347.99
          3         348081.14   470082.25
          4          46609.63    21472.48
          5           8965.80         NaN
southeast 0         826029.55  1420619.78
          1         585202.76   715066.23
          2         360936.28   677142.84
          3         287678.69   358065.90
          4          72255.12         NaN
          5          60692.65         NaN
southwest 0         876219.52   771294.22
          1         535306.23   276399.64
          2         357878.89   638679.83
          3         276805.98   108084.41
          4          46408.47    58124.36
          5          48530.01    19023.26