In [1]:
import numpy as np
import pandas as pd

In [15]:
df_sales = pd.read_csv(r'C:\Users\aniks\PycharmProjects\mlp-besant\data\sales_data_sample.csv')
df_sales

,TransactionID,Date,Region,SalesPerson,Product,Quantity,UnitPrice,Discount,Category,CustomerType
0,1,2025-01-01,North,Rahul,Laptop,2,60000,5,Electronics,Regular
1,2,2025-01-02,South,Meena,Mouse,5,800,0,Accessories,New
2,3,2025-01-03,East,Ajay,Keyboard,3,1200,10,Accessories,Regular
3,4,2025-01-04,West,Priya,Laptop,1,62000,0,Electronics,Regular
4,5,2025-01-05,North,Karan,Mobile,4,25000,5,Electronics,New
5,6,2025-01-06,East,Rahul,Tablet,2,18000,0,Electronics,Regular
6,7,2025-01-07,South,Meena,Charger,6,500,0,Accessories,New
7,8,2025-01-08,North,Priya,Laptop,3,58000,10,Electronics,Regular
8,9,2025-01-09,West,Ajay,Mobile,2,27000,5,Electronics,Regular
9,10,2025-01-10,East,Karan,Keyboard,5,1000,0,Accessories,New
10,11,2025-01-11,South,Rahul,Laptop,1,61000,0,Electronics,Regular
11,12,2025-01-12,North,Meena,Mouse,4,850,5,Accessories,New
12,13,2025-01-13,East,Priya,Tablet,3,19000,10,Electronics,Regular
13,14,2025-01-14,West,Ajay,Laptop,2,63000,0,Electronics,New
14,15,2025-01-15,North,Karan,Charger,5,550,0,Accessories,Regular
15,16,2025-01-16,South,Rahul,Keyboard,4,1100,0,Accessories,New
16,17,2025-01-17,East,Meena,Mobile,3,26000,5,Electronics,Regular
17,18,2025-01-18,West,Priya,Laptop,2,60000,5,Electronics,New
18,19,2025-01-19,North,Ajay,Tablet,4,18500,10,Electronics,Regular
19,20,2025-01-20,South,Karan,Mouse,6,750,0,Accessories,New

In [16]:
# check columns
df_sales.columns

Index(['TransactionID', 'Date', 'Region', 'SalesPerson', 'Product', 'Quantity',
       'UnitPrice', 'Discount', 'Category', 'CustomerType'],
      dtype='str')

In [17]:
# check columns types
df_sales.dtypes

TransactionID    int64
Date               str
Region             str
SalesPerson        str
Product            str
Quantity         int64
UnitPrice        int64
Discount         int64
Category           str
CustomerType       str
dtype: object

In [18]:
# check dataframe structure
df_sales.shape

(20, 10)

In [20]:
# check duplicates
df_sales.duplicated().sum()

np.int64(0)

In [21]:
# checking null values in columns
df_sales.isna().sum()

TransactionID    0
Date             0
Region           0
SalesPerson      0
Product          0
Quantity         0
UnitPrice        0
Discount         0
Category         0
CustomerType     0
dtype: int64

In [25]:
# Q1. Calculate Total Sales Amount for each transaction using a new column
total_sales = df_sales['Quantity'] * df_sales['UnitPrice'] - (df_sales['Quantity'] * df_sales['UnitPrice'])*df_sales['Discount']/100
df_sales['total_sales'] = total_sales
df_sales

,TransactionID,Date,Region,SalesPerson,Product,Quantity,UnitPrice,Discount,Category,CustomerType,total_sales
0,1,2025-01-01,North,Rahul,Laptop,2,60000,5,Electronics,Regular,114000.0
1,2,2025-01-02,South,Meena,Mouse,5,800,0,Accessories,New,4000.0
2,3,2025-01-03,East,Ajay,Keyboard,3,1200,10,Accessories,Regular,3240.0
3,4,2025-01-04,West,Priya,Laptop,1,62000,0,Electronics,Regular,62000.0
4,5,2025-01-05,North,Karan,Mobile,4,25000,5,Electronics,New,95000.0
5,6,2025-01-06,East,Rahul,Tablet,2,18000,0,Electronics,Regular,36000.0
6,7,2025-01-07,South,Meena,Charger,6,500,0,Accessories,New,3000.0
7,8,2025-01-08,North,Priya,Laptop,3,58000,10,Electronics,Regular,156600.0
8,9,2025-01-09,West,Ajay,Mobile,2,27000,5,Electronics,Regular,51300.0
9,10,2025-01-10,East,Karan,Keyboard,5,1000,0,Accessories,New,5000.0
10,11,2025-01-11,South,Rahul,Laptop,1,61000,0,Electronics,Regular,61000.0
11,12,2025-01-12,North,Meena,Mouse,4,850,5,Accessories,New,3230.0
12,13,2025-01-13,East,Priya,Tablet,3,19000,10,Electronics,Regular,51300.0
13,14,2025-01-14,West,Ajay,Laptop,2,63000,0,Electronics,New,126000.0
14,15,2025-01-15,North,Karan,Charger,5,550,0,Accessories,Regular,2750.0
15,16,2025-01-16,South,Rahul,Keyboard,4,1100,0,Accessories,New,4400.0
16,17,2025-01-17,East,Meena,Mobile,3,26000,5,Electronics,Regular,74100.0
17,18,2025-01-18,West,Priya,Laptop,2,60000,5,Electronics,New,114000.0
18,19,2025-01-19,North,Ajay,Tablet,4,18500,10,Electronics,Regular,66600.0
19,20,2025-01-20,South,Karan,Mouse,6,750,0,Accessories,New,4500.0

In [27]:
# Q2. Find total sales by each Region.
df_sales.groupby('Region')['total_sales'].sum()

Region
East     169640.0
North    438180.0
South     76900.0
West     353300.0
Name: total_sales, dtype: float64

In [28]:
# Q3. Display all transactions where Discount is greater than 5%.
df_sales[df_sales['Discount'] > 5]

,TransactionID,Date,Region,SalesPerson,Product,Quantity,UnitPrice,Discount,Category,CustomerType,total_sales
2,3,2025-01-03,East,Ajay,Keyboard,3,1200,10,Accessories,Regular,3240.0
7,8,2025-01-08,North,Priya,Laptop,3,58000,10,Electronics,Regular,156600.0
12,13,2025-01-13,East,Priya,Tablet,3,19000,10,Electronics,Regular,51300.0
18,19,2025-01-19,North,Ajay,Tablet,4,18500,10,Electronics,Regular,66600.0

In [29]:
# 4. Group data by Category and find the average UnitPrice for each.
df_sales.groupby('Category')['UnitPrice'].mean()

Category
Accessories      843.750000
Electronics    41458.333333
Name: UnitPrice, dtype: float64

In [39]:
# 5. Find the top 2 SalesPersons with the highest total sales amount.
df_sales.sort_values('total_sales', ascending=False).iloc[:2]

,TransactionID,Date,Region,SalesPerson,Product,Quantity,UnitPrice,Discount,Category,CustomerType,total_sales
7,8,2025-01-08,North,Priya,Laptop,3,58000,10,Electronics,Regular,156600.0
13,14,2025-01-14,West,Ajay,Laptop,2,63000,0,Electronics,New,126000.0

In [33]:
# 6. Filter records for only Electronics category where sales are above ₹50,000.
df_sales[(df_sales['Category'] == 'Electronics') & (df_sales['total_sales'] > 50000)]

,TransactionID,Date,Region,SalesPerson,Product,Quantity,UnitPrice,Discount,Category,CustomerType,total_sales
0,1,2025-01-01,North,Rahul,Laptop,2,60000,5,Electronics,Regular,114000.0
3,4,2025-01-04,West,Priya,Laptop,1,62000,0,Electronics,Regular,62000.0
4,5,2025-01-05,North,Karan,Mobile,4,25000,5,Electronics,New,95000.0
7,8,2025-01-08,North,Priya,Laptop,3,58000,10,Electronics,Regular,156600.0
8,9,2025-01-09,West,Ajay,Mobile,2,27000,5,Electronics,Regular,51300.0
10,11,2025-01-11,South,Rahul,Laptop,1,61000,0,Electronics,Regular,61000.0
12,13,2025-01-13,East,Priya,Tablet,3,19000,10,Electronics,Regular,51300.0
13,14,2025-01-14,West,Ajay,Laptop,2,63000,0,Electronics,New,126000.0
16,17,2025-01-17,East,Meena,Mobile,3,26000,5,Electronics,Regular,74100.0
17,18,2025-01-18,West,Priya,Laptop,2,60000,5,Electronics,New,114000.0
18,19,2025-01-19,North,Ajay,Tablet,4,18500,10,Electronics,Regular,66600.0

In [34]:
# 7. Sort the dataset by Date and SalesPerson in ascending order.
df_sales.sort_values(['Date','SalesPerson'])

,TransactionID,Date,Region,SalesPerson,Product,Quantity,UnitPrice,Discount,Category,CustomerType,total_sales
0,1,2025-01-01,North,Rahul,Laptop,2,60000,5,Electronics,Regular,114000.0
1,2,2025-01-02,South,Meena,Mouse,5,800,0,Accessories,New,4000.0
2,3,2025-01-03,East,Ajay,Keyboard,3,1200,10,Accessories,Regular,3240.0
3,4,2025-01-04,West,Priya,Laptop,1,62000,0,Electronics,Regular,62000.0
4,5,2025-01-05,North,Karan,Mobile,4,25000,5,Electronics,New,95000.0
5,6,2025-01-06,East,Rahul,Tablet,2,18000,0,Electronics,Regular,36000.0
6,7,2025-01-07,South,Meena,Charger,6,500,0,Accessories,New,3000.0
7,8,2025-01-08,North,Priya,Laptop,3,58000,10,Electronics,Regular,156600.0
8,9,2025-01-09,West,Ajay,Mobile,2,27000,5,Electronics,Regular,51300.0
9,10,2025-01-10,East,Karan,Keyboard,5,1000,0,Accessories,New,5000.0
10,11,2025-01-11,South,Rahul,Laptop,1,61000,0,Electronics,Regular,61000.0
11,12,2025-01-12,North,Meena,Mouse,4,850,5,Accessories,New,3230.0
12,13,2025-01-13,East,Priya,Tablet,3,19000,10,Electronics,Regular,51300.0
13,14,2025-01-14,West,Ajay,Laptop,2,63000,0,Electronics,New,126000.0
14,15,2025-01-15,North,Karan,Charger,5,550,0,Accessories,Regular,2750.0
15,16,2025-01-16,South,Rahul,Keyboard,4,1100,0,Accessories,New,4400.0
16,17,2025-01-17,East,Meena,Mobile,3,26000,5,Electronics,Regular,74100.0
17,18,2025-01-18,West,Priya,Laptop,2,60000,5,Electronics,New,114000.0
18,19,2025-01-19,North,Ajay,Tablet,4,18500,10,Electronics,Regular,66600.0
19,20,2025-01-20,South,Karan,Mouse,6,750,0,Accessories,New,4500.0

In [38]:
# 8. Find the number of transactions for each CustomerType (Regular vs New)
df_sales.groupby('CustomerType').size()

CustomerType
New         9
Regular    11
Name: TransactionID, dtype: int64

In [37]:
df_sales.groupby("CustomerType")["TransactionID"].nunique()

CustomerType
New         9
Regular    11
Name: TransactionID, dtype: int64

In [42]:
# 9. Get the most frequently sold product in each region.
df_sales.groupby('Region')['Product'].apply(lambda x: x.mode().iat[0])

Region
East     Keyboard
North      Laptop
South       Mouse
West       Laptop
Name: Product, dtype: str

In [45]:
df_sales.groupby('Region')['Product'].sum()

Region
East       KeyboardTabletKeyboardTabletMobile
North    LaptopMobileLaptopMouseChargerTablet
South         MouseChargerLaptopKeyboardMouse
West                 LaptopMobileLaptopLaptop
Name: Product, dtype: str

In [47]:
# 10. Pivot Table: Create a pivot table showing total sales by Region and Category.
pd.pivot_table(df_sales,columns=['Region','Category'] ,  values='total_sales', aggfunc='sum')

Region             East                   North                   South  \
Category    Accessories Electronics Accessories Electronics Accessories
total_sales      8240.0    161400.0      5980.0    432200.0     15900.0

Region                         West
Category    Electronics Electronics
total_sales     61000.0    353300.0

In [49]:
pd.pivot_table(
    df_sales,
    index="Region",
    columns="Category",
    values="total_sales",
    aggfunc="sum",
    fill_value=0
)

Category  Accessories  Electronics
Region
East           8240.0     161400.0
North          5980.0     432200.0
South         15900.0      61000.0
West              0.0     353300.0

In [54]:
pivot_df = pd.pivot_table(
    df_sales,
    index="Region",
    columns="Category",
    values="total_sales",
    aggfunc="sum",
    fill_value=0
)

# pivot_df.reset_index()
pivot_df.style

In [52]:
# print(pivot_df)

Category  Accessories  Electronics
Region
East           8240.0     161400.0
North          5980.0     432200.0
South         15900.0      61000.0
West              0.0     353300.0